name: Publish

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Publish Artifact
        env:
          RELEASE_TAG_NAME: ${{ github.event.inputs.version }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          OSS_STAGING_PROFILE_ID: ${{ secrets.OSS_STAGING_PROFILE_ID }}
          OSS_SIGNING_KEY_ID: ${{ secrets.OSS_SIGNING_KEY_ID }}
          OSS_SIGNING_PASSWORD: ${{ secrets.OSS_SIGNING_PASSWORD }}
          OSS_SIGNING_KEY: ${{ secrets.OSS_SIGNING_KEY }}
        run: |
          echo "version=${{ github.event.inputs.version }},username=${{ secrets.OSS_USERNAME }},pass=${{ secrets.OSS_PASSWORD }},profileId=${{ secrets.OSS_STAGING_PROFILE_ID }},sigKeyId=${{ secrets.OSS_SIGNING_KEY_ID }},sigPass=${{ secrets.OSS_SIGNING_PASSWORD }}"
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace