name: Publish

on:
  release:
    types: [ created ]

jobs:
  deploy:
    timeout-minutes: 45
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: ./.github/actions/gradle-cache

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Deploy release
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          OSS_STAGING_PROFILE_ID: ${{ secrets.OSS_STAGING_PROFILE_ID }}
          OSS_SIGNING_KEY_ID: ${{ secrets.OSS_SIGNING_KEY_ID }}
          OSS_SIGNING_PASSWORD: ${{ secrets.OSS_SIGNING_PASSWORD }}
          OSS_SIGNING_KEY: ${{ secrets.OSS_SIGNING_KEY }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository